# Generated by Django 4.1.1 on 2022-10-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saradpavanapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefront',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
