# Generated by Django 4.1.1 on 2022-10-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saradpavanapp', '0002_moviefront_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviefront',
            name='video',
            field=models.FileField(default=0, upload_to='photos'),
            preserve_default=False,
        ),
    ]
