# Generated by Django 4.1.1 on 2022-10-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saradpavanapp', '0005_contact_message_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='full_name',
        ),
    ]
