# Generated by Django 4.1.1 on 2022-10-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saradpavanapp', '0007_alter_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='full_name',
            new_name='name',
        ),
    ]
