# Generated by Django 4.1.1 on 2022-10-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saradpavanapp', '0008_rename_full_name_contact_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
